#!/bin/bash
set -e 
SPOTX_SCRIPT="/home/yazid/Downloads/spotx.sh"

[ -f "$SPOTX_SCRIPT" ] || exit 1

# Uninstall Spotify
if ! flatpak list | grep -q "com.spotify.Client"; then
    echo "Spotify not found. Installing Spotify..."
    flatpak install -y flathub com.spotify.Client
    cd "/home/yazid/Downloads" && bash spotx.sh
else
    echo "Spotify is already installed. Proceeding..."
    flatpak uninstall -y com.spotify.Client
    rm -r ~/.var/app/com.spotify.Client
    flatpak install -y flathub com.spotify.Client

fi
